# Generated by Django 6.0.1 on 2026-02-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(default='Quiénes somos', max_length=120)),
                ('about_body', models.TextField(default='Somos una plataforma de rifas. Participa subiendo tu comprobante de transferencia.')),
                ('policy_title', models.CharField(default='Políticas de la rifa', max_length=120)),
                ('policy_body', models.TextField(default='La compra queda PENDIENTE hasta verificación del comprobante.\nNo se aceptan comprobantes ilegibles o alterados.\nEl sorteo se realiza en la fecha indicada en cada rifa.')),
                ('payment_title', models.CharField(default='Métodos de pago', max_length=120)),
                ('payment_body', models.TextField(default='Transferencia bancaria / Depósito.\nZelle.\nPayPal.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenido del sitio',
                'verbose_name_plural': 'Contenido del sitio',
            },
        ),
    ]
