# Generated by Django 6.0.1 on 2026-02-02 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0002_sitecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='public_reference',
            field=models.CharField(blank=True, help_text='Código para que el cliente consulte su compra (recomendado).', max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='rifas.ticketpurchase')),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='rifas.raffle')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
                'ordering': ['number'],
                'constraints': [models.UniqueConstraint(fields=('raffle', 'number'), name='uniq_raffle_ticket_number')],
            },
        ),
    ]
