# Generated by Django 6.0.1 on 2026-02-02 04:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0003_ticketpurchase_public_reference_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='bonus_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Boletos de oferta (gratis).'),
        ),
        migrations.AddField(
            model_name='ticketpurchase',
            name='total_tickets',
            field=models.PositiveIntegerField(default=0, help_text='Total de boletos asignados (pagados + oferta).'),
        ),
        migrations.AlterField(
            model_name='ticketpurchase',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Boletos pagados.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='RaffleOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_quantity', models.PositiveIntegerField(help_text='Compra N', validators=[django.core.validators.MinValueValidator(1)])),
                ('bonus_quantity', models.PositiveIntegerField(help_text='Recibe M gratis', validators=[django.core.validators.MinValueValidator(1)])),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='rifas.raffle')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'ordering': ['-created_at'],
            },
        ),
    ]
