# Generated by Django 6.0.1 on 2026-02-02 23:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0004_ticketpurchase_bonus_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='image',
            field=models.ImageField(blank=True, help_text='Opcional. Imagen principal.', null=True, upload_to='raffles/'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='price_per_ticket',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ticketpurchase',
            name='total_amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='RaffleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='raffles/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rifas.raffle')),
            ],
            options={
                'verbose_name': 'Imagen de rifa',
                'verbose_name_plural': 'Imágenes de rifa',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
