# Generated by Django 6.0.1 on 2026-02-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0005_alter_raffle_image_alter_raffle_price_per_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffleoffer',
            name='min_paid_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Mínimo de boletos pagados para que aplique la oferta (0 = sin mínimo).'),
        ),
    ]
