# Generated by Django 6.0.1 on 2026-02-02 23:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0006_raffleoffer_min_paid_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='min_purchase_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Mínimo de boletos pagados por compra (ej: 1, 5, 10).', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
