# Generated by Django 6.0.1 on 2026-02-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0007_raffle_min_purchase_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=80)),
                ('account_number', models.CharField(max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='banks/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cuenta bancaria',
                'verbose_name_plural': 'Cuentas bancarias',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='payment_account_type',
            field=models.CharField(default='Cuenta de Ahorro', max_length=120),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='payment_currency',
            field=models.CharField(default='DOP', max_length=10),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='payment_holder_name',
            field=models.CharField(default='Federico A. Grullon', max_length=120),
        ),
    ]
