# Generated by Django 6.0.1 on 2026-02-03 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0008_bankaccount_sitecontent_payment_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Banco usado para la transferencia (seleccionado por el cliente).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='rifas.bankaccount'),
        ),
    ]
