# Generated by Django 6.0.1 on 2026-02-03 10:56

import rifas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0009_ticketpurchase_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='video',
            field=models.FileField(blank=True, help_text='Opcional. Video promocional (MP4/WebM, máximo 20 segundos).', null=True, upload_to='raffles/videos/', validators=[rifas.models.validate_video_file]),
        ),
    ]
