# Generated by Django 6.0.1 on 2026-02-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0010_raffle_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='terms_body',
            field=models.TextField(default='Al comprar boletos aceptas nuestros términos y condiciones.\nLa compra queda PENDIENTE hasta verificación del comprobante.\nNo se aceptan comprobantes ilegibles o alterados.\nEl sorteo se realiza en la fecha indicada en cada rifa.'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='terms_title',
            field=models.CharField(default='Términos y condiciones', max_length=120),
        ),
    ]
