# Generated by Django 6.0.1 on 2026-02-03 11:07

import rifas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0011_sitecontent_terms_body_sitecontent_terms_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='delivery_media',
            field=models.FileField(blank=True, help_text='Opcional. Foto o video de la entrega del premio.', null=True, upload_to='raffles/history/delivery/', validators=[rifas.models.validate_history_media_file]),
        ),
        migrations.AddField(
            model_name='raffle',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text='Opcional. Observación de la entrega (ej: fecha, lugar).'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='finished_at',
            field=models.DateTimeField(blank=True, help_text='Opcional. Fecha/hora real cuando se culminó (si difiere de la fecha de sorteo).', null=True),
        ),
        migrations.AddField(
            model_name='raffle',
            name='history_cover_image',
            field=models.ImageField(blank=True, help_text='Opcional. Portada para el historial (una sola foto).', null=True, upload_to='raffles/history/'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='show_in_history',
            field=models.BooleanField(default=True, help_text='Si está desactivado, esta rifa no se mostrará en el historial público.'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='winner_media',
            field=models.FileField(blank=True, help_text='Opcional. Foto o video del ganador(a).', null=True, upload_to='raffles/history/winner/', validators=[rifas.models.validate_history_media_file]),
        ),
        migrations.AddField(
            model_name='raffle',
            name='winner_name',
            field=models.CharField(blank=True, help_text='Opcional. Nombre del ganador(a) para mostrar en el historial.', max_length=120),
        ),
        migrations.AddField(
            model_name='raffle',
            name='winner_notes',
            field=models.TextField(blank=True, help_text='Opcional. Observación del ganador(a) (ej: ciudad, IG, etc.).'),
        ),
    ]
