# Generated by Django 6.0.1 on 2026-02-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0012_raffle_delivery_media_raffle_delivery_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpurchase',
            name='phone',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AddIndex(
            model_name='ticketpurchase',
            index=models.Index(fields=['raffle', 'phone'], name='idx_purchase_raffle_phone'),
        ),
        migrations.AddIndex(
            model_name='ticketpurchase',
            index=models.Index(fields=['status', 'created_at'], name='idx_purchase_status_created'),
        ),
    ]
