# Generated by Django 6.0.1 on 2026-02-05 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0013_alter_ticketpurchase_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_password_change', models.BooleanField(default=False, help_text='Si está activo, el usuario será obligado a cambiar su contraseña al entrar.')),
                ('password_hash_at_force', models.CharField(blank=True, help_text='Hash de contraseña en el momento de activar el forzado (interno).', max_length=128)),
                ('forced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguridad del usuario',
                'verbose_name_plural': 'Seguridad de usuarios',
            },
        ),
    ]
