# Generated by Django 6.0.1 on 2026-02-05 03:18

import rifas.models
from django.db import migrations, models


def backfill_customers(apps, schema_editor):
    TicketPurchase = apps.get_model("rifas", "TicketPurchase")
    Customer = apps.get_model("rifas", "Customer")

    # Build from existing purchases (best-effort, idempotent).
    for p in TicketPurchase.objects.exclude(phone__isnull=True).exclude(phone="").iterator(chunk_size=2000):
        phone = (p.phone or "").strip()
        if not phone:
            continue
        obj, _created = Customer.objects.get_or_create(
            phone=phone,
            defaults={
                "full_name": (p.full_name or "").strip(),
                "email": (p.email or "").strip(),
                "first_purchase_at": p.created_at,
                "last_purchase_at": p.created_at,
                "total_purchases": 0,
                "total_paid_tickets": 0,
                "total_bonus_tickets": 0,
                "total_amount": 0,
            },
        )
        # Keep latest known name/email (don't overwrite with blank).
        updated = False
        if p.full_name and (not obj.full_name or obj.full_name != p.full_name):
            obj.full_name = p.full_name
            updated = True
        if p.email and (not obj.email or obj.email != p.email):
            obj.email = p.email
            updated = True
        # First/last purchase markers
        if p.created_at and (obj.first_purchase_at is None or p.created_at < obj.first_purchase_at):
            obj.first_purchase_at = p.created_at
            updated = True
        if p.created_at and (obj.last_purchase_at is None or p.created_at > obj.last_purchase_at):
            obj.last_purchase_at = p.created_at
            updated = True
        if updated:
            obj.save()

    # Aggregate totals per customer (simple approach).
    for c in Customer.objects.all().iterator(chunk_size=2000):
        agg = (
            TicketPurchase.objects.filter(phone=c.phone)
            .aggregate(
                total_purchases=models.Count("id"),
                total_paid=models.Sum("quantity"),
                total_bonus=models.Sum("bonus_quantity"),
                total_amount=models.Sum("total_amount"),
            )
        )
        c.total_purchases = int(agg.get("total_purchases") or 0)
        c.total_paid_tickets = int(agg.get("total_paid") or 0)
        c.total_bonus_tickets = int(agg.get("total_bonus") or 0)
        c.total_amount = int(agg.get("total_amount") or 0)
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0014_usersecurity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='video',
            field=models.FileField(blank=True, help_text='Opcional. Video promocional (MP4/WebM/MOV, máximo 20 segundos).', null=True, upload_to='raffles/videos/', validators=[rifas.models.validate_video_file]),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=40, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('first_purchase_at', models.DateTimeField(blank=True, null=True)),
                ('last_purchase_at', models.DateTimeField(blank=True, null=True)),
                ('total_purchases', models.PositiveIntegerField(default=0)),
                ('total_paid_tickets', models.PositiveIntegerField(default=0)),
                ('total_bonus_tickets', models.PositiveIntegerField(default=0)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'indexes': [models.Index(fields=['email'], name='idx_customer_email'), models.Index(fields=['last_purchase_at'], name='idx_customer_last_purchase')],
            },
        ),
        migrations.RunPython(backfill_customers, migrations.RunPython.noop),
    ]
