# Generated by Django 6.0.1 on 2026-02-05 03:56

import rifas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0015_alter_raffle_video_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='ceo_name',
            field=models.CharField(default='FEDERICO ANTONIO GRULLON DE LEON', help_text='Nombre del CEO (se muestra en el pie de página).', max_length=160),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='ceo_phone',
            field=models.CharField(default='8296058290', help_text='Teléfono de contacto del CEO (se muestra en el pie de página).', max_length=30),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='video',
            field=models.FileField(blank=True, help_text='Opcional. Video promocional (MP4/MOV recomendado en H.264, máximo 20 segundos).', null=True, upload_to='raffles/videos/', validators=[rifas.models.validate_video_file]),
        ),
    ]
