# Generated by Django 6.0.1 on 2026-02-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0016_sitecontent_ceo_name_sitecontent_ceo_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='ceo_instagram_url',
            field=models.URLField(blank=True, default='', help_text='URL del Instagram del CEO (ej: https://instagram.com/usuario).'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='ceo_tiktok_url',
            field=models.URLField(blank=True, default='', help_text='URL del TikTok del CEO (ej: https://tiktok.com/@usuario).'),
        ),
    ]
