# Generated by Django 6.0.1 on 2026-02-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0017_sitecontent_ceo_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='winner_ticket_number',
            field=models.PositiveIntegerField(blank=True, help_text='Opcional. Número de boleto ganador (para mostrar en el historial).', null=True),
        ),
    ]
