# Generated by Django 6.0.1 on 2026-02-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0018_raffle_winner_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='Logo del sitio (recomendado PNG transparente).', null=True, upload_to='site/'),
        ),
    ]
