# Generated by Django 6.0.1 on 2026-02-13 03:36

import django.db.models.deletion
import rifas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0019_sitecontent_site_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo del banco. Recomendado: PNG cuadrado 512×512.', null=True, upload_to='banks/'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='delivery_media',
            field=models.FileField(blank=True, help_text='Opcional. Foto o video de la entrega del premio.\nFoto recomendado: 3:4 (ej: 1200×1600). Video recomendado: MP4 (H.264).', null=True, upload_to='raffles/history/delivery/', validators=[rifas.models.validate_history_media_file]),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='history_cover_image',
            field=models.ImageField(blank=True, help_text='Opcional. Portada para el historial (una sola foto).\nRecomendado: horizontal 16:9 (ej: 1200×675 o 1920×1080).', null=True, upload_to='raffles/history/'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='image',
            field=models.ImageField(blank=True, help_text='Opcional. Imagen principal.\nRecomendado: vertical 3:4 (ej: 1200×1600). Mínimo sugerido: 900×1200.', null=True, upload_to='raffles/'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='winner_media',
            field=models.FileField(blank=True, help_text='Opcional. Foto o video del ganador(a).\nFoto recomendado: 3:4 (ej: 1200×1600). Video recomendado: MP4 (H.264).', null=True, upload_to='raffles/history/winner/', validators=[rifas.models.validate_history_media_file]),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='winner_name',
            field=models.CharField(blank=True, help_text='Opcional. Si se deja vacío, se toma automáticamente del comprador del boleto ganador.', max_length=120),
        ),
        migrations.AlterField(
            model_name='raffleimage',
            name='image',
            field=models.ImageField(help_text='Imagen adicional. Recomendado: vertical 3:4 (ej: 1200×1600). Mínimo sugerido: 900×1200.', upload_to='raffles/'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='Logo del sitio. Recomendado: PNG cuadrado 512×512 (fondo transparente).', null=True, upload_to='site/'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('purchase_approved', 'Compra aprobada'), ('purchase_rejected', 'Compra rechazada'), ('purchase_deleted', 'Compra eliminada'), ('ticket_deleted', 'Boleto eliminado'), ('winner_set', 'Ganador asignado')], db_index=True, max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='Estado anterior')),
                ('to_status', models.CharField(blank=True, max_length=20, verbose_name='Estado nuevo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='Extra')),
                ('ip', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='rifas.ticketpurchase', verbose_name='Compra')),
                ('raffle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='rifas.raffle', verbose_name='Rifa')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='rifas.ticket', verbose_name='Boleto')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditoría',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='idx_audit_action_created'), models.Index(fields=['raffle', 'created_at'], name='idx_audit_raffle_created'), models.Index(fields=['purchase', 'created_at'], name='idx_audit_purchase_created')],
            },
        ),
    ]
