# Generated by Django 6.0.1 on 2026-02-13 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0020_alter_bankaccount_logo_alter_raffle_delivery_media_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RaffleCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ticket_price', models.PositiveIntegerField(verbose_name='Precio por boleto')),
                ('product_cost', models.PositiveIntegerField(default=0, verbose_name='Costo del producto')),
                ('shipping_cost', models.PositiveIntegerField(default=0, verbose_name='Envío')),
                ('advertising_cost', models.PositiveIntegerField(default=0, verbose_name='Publicidad')),
                ('other_costs', models.PositiveIntegerField(default=0, verbose_name='Otros gastos')),
                ('desired_margin_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Margen deseado (%)')),
                ('offer_buy_quantity', models.PositiveIntegerField(default=0, verbose_name='Oferta compra N')),
                ('offer_bonus_quantity', models.PositiveIntegerField(default=0, verbose_name='Oferta gratis M')),
                ('offer_min_paid_quantity', models.PositiveIntegerField(default=0, verbose_name='Oferta mínimo pagados')),
                ('total_cost', models.PositiveIntegerField(default=0, verbose_name='Costos totales')),
                ('revenue_needed', models.PositiveIntegerField(default=0, verbose_name='Ingresos meta')),
                ('break_even_tickets', models.PositiveIntegerField(default=0, verbose_name='Boletos punto de equilibrio')),
                ('paid_tickets_needed', models.PositiveIntegerField(default=0, verbose_name='Boletos pagados sugeridos')),
                ('bonus_tickets', models.PositiveIntegerField(default=0, verbose_name='Boletos gratis')),
                ('total_issued', models.PositiveIntegerField(default=0, verbose_name='Total emitidos')),
                ('expected_revenue', models.PositiveIntegerField(default=0, verbose_name='Ingresos estimados')),
                ('expected_profit', models.IntegerField(default=0, verbose_name='Ganancia estimada')),
                ('max_tickets', models.PositiveIntegerField(default=0, verbose_name='Máximo boletos (rifa)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raffle_calculations', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='rifas.raffle', verbose_name='Rifa')),
            ],
            options={
                'verbose_name': 'Cálculo de rifa',
                'verbose_name_plural': 'Cálculos de rifas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['raffle', 'created_at'], name='idx_calc_raffle_created'), models.Index(fields=['created_by', 'created_at'], name='idx_calc_user_created')],
            },
        ),
    ]
