# Generated by Django 6.0.1 on 2026-02-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0021_rafflecalculation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='raffle',
            index=models.Index(fields=['is_active', 'draw_date'], name='idx_raffle_active_draw'),
        ),
        migrations.AddIndex(
            model_name='raffle',
            index=models.Index(fields=['show_in_history', 'draw_date'], name='idx_raffle_hist_draw'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['raffle', 'number'], name='idx_ticket_raffle_number'),
        ),
    ]
