# Generated by Django 6.0.1 on 2026-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rifas", "0022_raffle_idx_raffle_active_draw_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="raffle",
            name="show_draw_date",
            field=models.BooleanField(
                default=True,
                help_text="Si está desactivado, no se mostrará la fecha del sorteo en la web.",
                verbose_name="Mostrar fecha",
            ),
        ),
    ]

