# Generated by Django 6.0.1 on 2026-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rifas", "0023_raffle_show_draw_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="raffle",
            name="draw_source_text",
            field=models.CharField(
                blank=True,
                help_text="Texto opcional que se muestra debajo del 100% (ej: últimos 3 números de Pega 4, Lotería Real).",
                max_length=280,
                verbose_name="Texto de sorteo (lotería)",
            ),
        ),
    ]

