# Generated by Django 6.0.1 on 2026-02-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rifas", "0024_raffle_draw_source_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="owner_name",
            field=models.CharField(
                blank=True,
                help_text="Nombre del titular de la cuenta (para distinguir cuentas de diferentes propietarios).",
                max_length=120,
                verbose_name="Propietario / Titular",
            ),
        ),
    ]

