# Generated by Django 6.0.1 on 2026-03-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0025_bankaccount_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='show_in_my_tickets_search',
            field=models.BooleanField(default=True, help_text='Si está desactivado, esta rifa no aparecerá en el selector de la página “Mis boletos”.', verbose_name='Mostrar en Mis boletos'),
        ),
    ]
