# Generated by Django 6.0.1 on 2026-03-09 02:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0026_raffle_show_in_my_tickets_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='manual_progress_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='0–100. Solo se usa si “Usar progreso manual” está activo.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progreso manual (%)'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='use_manual_progress',
            field=models.BooleanField(default=False, help_text='Si está activo, la web mostrará el progreso manual en lugar del progreso real (boletos aprobados).', verbose_name='Usar progreso manual'),
        ),
    ]
