"""
Django settings for rifa_site project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import logging

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, set SECRET_KEY via environment variable.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-9&*y8he_@4q1ssz6h30y0s!_1)_gf)(c2r0l@bn8f__9+c5=c%",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if o.strip()
]

# Railway/Proxy friendliness
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Security defaults for production
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    # Start low (safe) and increase once you're sure HTTPS is always on.
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "60"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get("SECURE_HSTS_INCLUDE_SUBDOMAINS", "0") == "1"
    SECURE_HSTS_PRELOAD = os.environ.get("SECURE_HSTS_PRELOAD", "0") == "1"
    # Redirect all HTTP -> HTTPS (Railway sets X-Forwarded-Proto=https).
    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "1") == "1"
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = os.environ.get("SECURE_REFERRER_POLICY", "same-origin")
    SECURE_CROSS_ORIGIN_OPENER_POLICY = os.environ.get("SECURE_CROSS_ORIGIN_OPENER_POLICY", "same-origin")
    # Helps prevent other sites from embedding/reading our resources.
    # Keep permissive enough for normal operation.
    SECURE_CROSS_ORIGIN_RESOURCE_POLICY = os.environ.get("SECURE_CROSS_ORIGIN_RESOURCE_POLICY", "same-site")
    SESSION_COOKIE_SAMESITE = os.environ.get("SESSION_COOKIE_SAMESITE", "Lax")
    CSRF_COOKIE_SAMESITE = os.environ.get("CSRF_COOKIE_SAMESITE", "Lax")

X_FRAME_OPTIONS = os.environ.get("X_FRAME_OPTIONS", "DENY")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sitemaps',
    'imagekit',
    'rifas.apps.RifasConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'rifas.middleware.AdminForcePasswordChangeMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rifa_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'rifas.context_processors.site_content',
            ],
        },
    },
]

WSGI_APPLICATION = 'rifa_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Default: SQLite for quick start.
# For MySQL set:
# - DB_ENGINE=mysql
# - DB_NAME, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT

DB_ENGINE = os.environ.get("DB_ENGINE", "sqlite").lower()

if DB_ENGINE == "mysql":
    # Use PyMySQL (pure python) to avoid Windows build issues.
    import pymysql  # type: ignore

    pymysql.install_as_MySQLdb()
    # Django 6+ expects mysqlclient >= 2.2.1; PyMySQL reports legacy version.
    # This keeps the backend happy while using PyMySQL.
    try:
        import MySQLdb  # type: ignore

        MySQLdb.__version__ = "2.2.1"
        MySQLdb.version_info = (2, 2, 1)
    except Exception:
        pass

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.environ.get("DB_NAME", "rifa_db"),
            "USER": os.environ.get("DB_USER", "root"),
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
            "HOST": os.environ.get("DB_HOST", "127.0.0.1"),
            "PORT": os.environ.get("DB_PORT", "3306"),
            # Keep connections open a bit (Railway proxies can drop idle conns).
            # Health checks will reconnect transparently if server dropped it.
            "CONN_MAX_AGE": int(os.environ.get("DB_CONN_MAX_AGE", "60")),
            "CONN_HEALTH_CHECKS": True,
            "OPTIONS": {
                "charset": "utf8mb4",
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
                # Timeouts (seconds). Helps with transient proxy hiccups.
                "connect_timeout": int(os.environ.get("DB_CONNECT_TIMEOUT", "15")),
                "read_timeout": int(os.environ.get("DB_READ_TIMEOUT", "30")),
                "write_timeout": int(os.environ.get("DB_WRITE_TIMEOUT", "30")),
            },
        }
    }
    # Optional SSL (often required by hosted DBs like Railway)
    if os.environ.get("DB_SSL", "0") == "1":
        DATABASES["default"]["OPTIONS"]["ssl"] = {}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "es-do"

LANGUAGES = [
    ("es", "Español"),
]

TIME_ZONE = 'America/Santo_Domingo'

USE_I18N = True

USE_TZ = True

# Logging (Railway/Gunicorn)
# Ensures 500 errors print tracebacks to stdout/stderr so Railway logs show the cause.
DJANGO_LOG_LEVEL = os.environ.get("DJANGO_LOG_LEVEL", "INFO").upper()
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "%(levelname)s %(name)s: %(message)s"},
        "verbose": {"format": "%(asctime)s %(levelname)s %(name)s: %(message)s"},
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        }
    },
    "root": {"handlers": ["console"], "level": DJANGO_LOG_LEVEL},
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
# Only collect compiled assets in production (avoid collecting Tailwind source files under static/src/)
# Use a prefix so `{% static 'dist/tailwind.css' %}` resolves correctly with manifest storage.
_static_dist = BASE_DIR / "static" / "dist"
if _static_dist.exists():
    STATICFILES_DIRS = [("dist", _static_dist)]
else:
    # Fallback for dev environments where dist isn't built yet
    STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []

# WhiteNoise (static files in production)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    }
}

# Media (user uploads: payment proofs, raffle images)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ImageKit: store generated cache files under /media/raffles/ so they are
# publicly servable by our production media_serve allowlist (prefix "raffles/").
# Versioned cache dir so new processors regenerate images (avoids stale cache files).
IMAGEKIT_CACHEFILE_DIR = "raffles/cache/v2"

# Upload limits (videos/admin uploads can be large; handlers will stream to disk).
# These guardrails prevent accidental huge posts, and can be tuned via env.
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get("DATA_UPLOAD_MAX_MEMORY_SIZE", str(100 * 1024 * 1024)))  # 100MB
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get("FILE_UPLOAD_MAX_MEMORY_SIZE", str(5 * 1024 * 1024)))  # 5MB (rest to temp files)

# In production, serve ONLY public media via Django if enabled (Railway).
# NOTE: This should be paired with a persistent volume mounted to MEDIA_ROOT.
SERVE_PUBLIC_MEDIA = os.environ.get("SERVE_PUBLIC_MEDIA", "0") == "1"

# Email (SendGrid SMTP recommended in production)
# Dev default: prints emails in terminal (no SMTP required)
_env_email_backend = (os.environ.get("EMAIL_BACKEND", "") or "").strip()
SENDGRID_API_KEY = (os.environ.get("SENDGRID_API_KEY", "") or "").strip()

if _env_email_backend:
    EMAIL_BACKEND = _env_email_backend
else:
    EMAIL_BACKEND = (
        "django.core.mail.backends.smtp.EmailBackend"
        if SENDGRID_API_KEY
        else "django.core.mail.backends.console.EmailBackend"
    )

# If SENDGRID_API_KEY is present and SMTP fields not provided, default to SendGrid SMTP.
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.sendgrid.net" if SENDGRID_API_KEY else "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "apikey" if SENDGRID_API_KEY else "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", SENDGRID_API_KEY if SENDGRID_API_KEY else "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "1") == "1"
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "GanaHoyRD <no-reply@rifas.local>")
EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", "10"))  # seconds

# Where purchase proof notifications go (admin inbox)
PURCHASE_NOTIFY_EMAIL = os.environ.get("PURCHASE_NOTIFY_EMAIL", "")
SEND_PURCHASE_EMAILS = os.environ.get("SEND_PURCHASE_EMAILS", "0") == "1"
SEND_CUSTOMER_EMAILS = os.environ.get("SEND_CUSTOMER_EMAILS", "0") == "1"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
